DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS DEPT_EMP;
DROP TABLE IF EXISTS DEPT_MANAGER;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS SALARIES;
DROP TABLE IF EXISTS TITLES;

CREATE TABLE DEPARTMENTS(
	DEPT_NO VARCHAR(100) NOT NULL,
	DEPT_NAME VARCHAR(100)NOT NULL);
COPY DEPARTMENTS(DEPT_NO,DEPT_NAME)
	FROM 'C:\Users\Wei_l\SQL-Challenger\EmployeeSQL\data\departments.csv'DELIMITER','CSV HEADER;

CREATE TABLE TITLES(
	TITLE_ID VARCHAR(40) NOT NULL,
	TITLE VARCHAR (100) NOT NULL);
COPY TITLES(TITLE_ID,TITLE)
	FROM 'C:\Users\Wei_l\SQL-Challenger\EmployeeSQL\data\titles.csv'DELIMITER','CSV HEADER;

CREATE TABLE EMPLOYEES(
	EMP_NO INT NOT NULL,
	EMP_TITLE_ID VARCHAR NOT NULL,
	BIRTH_DATE VARCHAR NOT NULL,
	FIRST_NAME VARCHAR NOT NULL,
	LAST_NAME VARCHAR NOT NULL,
	SEX VARCHAR(30) NOT NULL,
	HIRE_DATE VARCHAR NOT NULL);
COPY EMPLOYEES(EMP_NO,EMP_TITLE_ID,BIRTH_DATE,FIRST_NAME,LAST_NAME,SEX,HIRE_DATE)
	FROM 'C:\Users\Wei_l\SQL-Challenger\EmployeeSQL\data\employees.csv'DELIMITER','CSV HEADER;

CREATE TABLE DEPT_EMP(
	EMP_NO INT NOT NULL,
	DEPT_NO VARCHAR NOT NULL);
COPY DEPT_EMP(EMP_NO,DEPT_NO)
	FROM 'C:\Users\Wei_l\SQL-Challenger\EmployeeSQL\data\dept_emp.csv'DELIMITER','CSV HEADER;

CREATE TABLE DEPT_MANAGER(
	DEPT_NO VARCHAR(100) NOT NULL,
	EMP_NO INT NOT NULL);
COPY DEPT_MANAGER(DEPT_NO,EMP_NO)
	FROM 'C:\Users\Wei_l\SQL-Challenger\EmployeeSQL\data\dept_manager.csv'DELIMITER','CSV HEADER;
		
CREATE TABLE SALARIES(
	EMP_NO INT NOT NULL,
	SALARY FLOAT NOT NULL);
COPY SALARIES(EMP_NO,SALARY)
	FROM 'C:\Users\Wei_l\SQL-Challenger\EmployeeSQL\data\salaries.csv'DELIMITER','CSV HEADER;

ALTER TABLE DEPARTMENTS ADD PRIMARY KEY (DEPT_NO);
ALTER TABLE TITLES ADD PRIMARY KEY (TITLE_ID);
ALTER TABLE EMPLOYEES 
	ADD PRIMARY KEY (EMP_NO), 
	ADD FOREIGN KEY (EMP_TITLE_ID) REFERENCES TITLES(TITLE_ID) ON DELETE CASCADE;
ALTER TABLE DEPT_EMP
	ADD FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO) ON DELETE CASCADE, 
	ADD FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO) ON DELETE CASCADE;
ALTER TABLE DEPT_MANAGER 
	ADD FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO) ON DELETE CASCADE, 
	ADD FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO) ON DELETE CASCADE;
ALTER TABLE SALARIES
	ADD FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO) ON DELETE CASCADE;

